name: Deploy Bot to VPS
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload repo to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "."
          target: "/opt/telegram-bot"

      - name: Install deps & restart service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            APP_DIR="/opt/telegram-bot"
            VENV_DIR="$APP_DIR/venv"
            
            # Create environment file from secrets
            cat > "$APP_DIR/.env" << 'EOF'
            # Telegram Bot Configuration
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            TELEGRAM_API_ID=${{ secrets.TELEGRAM_API_ID }}
            TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }}
            
            # OpenAI Configuration
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            
            # Database Configuration
            DATABASE_URL=sqlite:///./bot.db
            
            # Environment
            ENVIRONMENT=production
            LOG_LEVEL=INFO
            
            # Bot Configuration
            BOT_USERNAME=${{ secrets.BOT_USERNAME }}
            WEBHOOK_URL=
            WEBHOOK_PORT=8443
            
            # Admin Configuration
            ADMIN_USER_IDS=${{ secrets.ADMIN_USER_IDS }}
            
            # Features
            ENABLE_ANALYTICS=true
            ENABLE_MONITORING=true
            ENABLE_AUTO_UPDATES=true
            
            # Rate Limiting
            RATE_LIMIT_REQUESTS=30
            RATE_LIMIT_WINDOW=60
            
            # Cache Configuration
            REDIS_URL=redis://localhost:6379/0
            CACHE_TTL=3600
            EOF
            
            # Secure the environment file
            chmod 600 "$APP_DIR/.env"
            
            # Ensure Python & venv
            if ! command -v python3 >/dev/null 2>&1; then
              sudo apt-get update -y
              sudo apt-get install -y python3 python3-venv python3-pip
            fi
            # Create venv if missing
            if [ ! -d "$VENV_DIR" ]; then
              python3 -m venv "$VENV_DIR"
            fi
            "$VENV_DIR/bin/pip" install --upgrade pip wheel
            if [ -f "$APP_DIR/requirements.txt" ]; then
              "$VENV_DIR/bin/pip" install -r "$APP_DIR/requirements.txt"
            fi
            # Pick correct module entry (-m bot OR -m bot.main)
            ENTRY="bot"
            [ -f "$APP_DIR/bot/main.py" ] && ENTRY="bot.main"
            # Update systemd unit if needed
            UNIT_FILE="/etc/systemd/system/telegram-bot.service"
            if [ -f "$UNIT_FILE" ]; then
              sudo sed -i "s|ExecStart=.*|ExecStart=$VENV_DIR/bin/python -m ${ENTRY}|g" "$UNIT_FILE" || true
              sudo systemctl daemon-reload || true
            fi
            # Enable/restart
            sudo systemctl enable telegram-bot || true
            sudo systemctl restart telegram-bot || sudo systemctl start telegram-bot
            echo "Deployment completed successfully"
