name: Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      - name: Install Ruff
        run: pip install "ruff==0.5.7"
      - name: Ruff Check (non-migrated paths)
        run: |
          echo "Ruff version:"; ruff --version
          # Ruff reads config from .ruff.toml, which excludes to_port/ by default.
          ruff check . --output-format=github
